-d C:\Users\Tommy\VHDPlus\Projects\FPGAir\impl\gwsynthesis\FPGAir.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Tommy\VHDPlus\Projects\FPGAir\const\FPGAir.cst
-cfg C:\Users\Tommy\VHDPlus\Projects\FPGAir\impl\pnr\device.cfg
-sdc C:\Users\Tommy\VHDPlus\Projects\FPGAir\const\FPGAir.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
